baseurl: /
theme: hugo-casper-two
languageCode: en-US
disqusShortname: ''
paginate: 6
canonifyurls: yes
params:
  RSSLink: ''
  author: EM
  authorAvatar: img/ghost-icon.png
  authorDescription: Your description here
  authorLocation: Bandung, ID
  authorWebsite: https://eueung.github.io
  copyright: © 2018
  cover: img/blog-cover.jpg
  customCSS: []
  description: Here is a description of your site.
  fbName: fakeghost
  githubName: eueung
  googleAnalytics: ''
  linkedinName: eueung
  logo: hugo-logo.png
  mediumName: ''
  metaDescription: ''
  orgDescription: Here is a description placeholder for your org
  orgName: EM
  orgWebsite: https://www.telematika.org
  pageNotFoundTitle: 404 - Page not found
  showSupport: yes
  singleViewStyle: casper
  subtitle: Port of Casper 2.x for Hugo
  title: Hugo Casper Two
  twitterName: faketryghost
permalinks:
  post: /post/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 200
    - name: Go
      url: /tags/golang/
      weight: 100
    - name: Categories
      url: /categories/
      weight: 99
    - name: External
      url: https://google.com/
      weight: 95
