baseurl         = "https://edata.ga"
theme = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
enableRobotsTXT = true

[params]
  title       = "Business Solution"
  subtitle    = "Data Science Service"
  copyright   = "© 2020"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "@Mezhoud90305294"
  #fbName = "fakeghost"
  githubName = "kmezhoud"
  linkedinName = "karim-mezhoud"
  mediumName = ""

  logo = ""
  orgName = "EM"
  orgWebsite = "https://edata.ga/"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "kirus"
  authorAvatar = "img/kmezhoud.jpg"
  authorLocation = "Tunisia, TN"
  authorWebsite = "https://kmezhoud.github.io"
  authorDescription = "Data Scientist"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


